export const DISPLAY_ALERT ='SHOW_ALERT'
export const CLEAR_ALERT ='CLEAR_ALERT'
export const SUBMIT_TRANSACTION_BEGIN = 'SUBMIT_TRANSACTION_BEGIN'
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const GET_DATA = "GET_DATA"
export const GET_TRANSACTIONS = "GET_TRANSACTIONS"
export const GET_ALL_LOANACCOUNTS = "GET_ALL_LOANACCOUNTS"
export const GET_ACTIVE_LOAN = "GET_ACTIVE_LOAN"

export const SETUP_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const SETUP_USER_ERROR = 'LOGIN_USER_ERROR'

export const RERENDER_COMPONENT = "RERENDER_COMPONENT"